add delete group by name API
ONSdigital/dp-identity-api pull request #105
Opened 2021-10-13 14:53 UTC by Marianasilvago

### What

Added Delete group endpoint

### How to review

Review code, tests, component tests

### Who can review

Anyone

2021-10-14 07:42 UTC, CarlHembrough requested changes

2021-10-14 07:42 UTC, CarlHembrough commented on features/groups.feature
> +        Given group "get-group-not-found" exists in the database
It's a bit confusing that the given clause suggests the group `exists in the database`, but then when the get request is made it returns a 404? Consider if the `Given` line can be removed.

2021-10-14 07:42 UTC, CarlHembrough commented on swagger.yaml
> +          description: "The list group details"
This description looks like it needs updating

2021-10-14 13:49 UTC, ChrysmOre commented on api/groups.go
> +//DeleteGroupHandler deletes the group for the given group id
I would recommend splitting this function up slightly differently whitespace-wise:
```suggestion
func (api *API) DeleteGroupHandler(ctx context.Context, w http.ResponseWriter, req *http.Request) (*models.SuccessResponse, *models.ErrorResponse) {
	vars := mux.Vars(req)
	group := models.Group{Name: vars["id"]}
	groupDeleteRequest := group.BuildDeleteGroupRequest(api.UserPoolId)

	_, err := api.CognitoClient.DeleteGroup(groupDeleteRequest)
	if err != nil {
		cognitoErr := models.NewCognitoError(ctx, err, "Cognito DeleteGroup request from Delete group endpoint")
		if cognitoErr.Code == models.NotFoundError {
			return nil, models.NewErrorResponse(http.StatusNotFound, nil, cognitoErr)
		}
		return nil, models.NewErrorResponse(http.StatusInternalServerError, nil, cognitoErr)
	}

	return &models.SuccessResponse{Status: http.StatusOK}, nil
}
```

2021-10-14 13:58 UTC, CarlHembrough submitted a review, later dismissed

2021-10-18 14:32 UTC, mike-kelly-methods commented on api/groups.go
> +	return &models.SuccessResponse{Status: http.StatusOK}, nil
According to the ticket, this should be returning a `http.StatusNoContent` instead of a `http.StatusOK`.

2021-10-18 14:33 UTC, mike-kelly-methods commented on api/groups_test.go
> +				So(successResponse.Status, ShouldEqual, http.StatusOK)
`http.StatusNoContent` instead of `http.StatusOK`.

2021-10-18 14:33 UTC, mike-kelly-methods commented on features/groups.feature
> +        Then the HTTP status code should be "200"
`204`

2021-10-18 14:33 UTC, mike-kelly-methods commented on features/groups.feature
> +    Scenario: GET /v1/groups/{id} and checking the response status 200
`204`

2021-10-18 14:35 UTC, mike-kelly-methods commented on api/groups_test.go
> +			"200 response from Cognito ",
`204`

2021-10-18 14:38 UTC, mike-kelly-methods commented on models/groups.go
> +// BuildDeleteGroupRequest builds a correctly populated DeleteGroupInput object using the Groups values
We normally add a small model unit test to the `models/groups_test.go` package too, but can see you've tested it in the main api package 👍

2021-10-18 15:02 UTC, mike-kelly-methods commented on api/groups.go
> +	return &models.SuccessResponse{Status: http.StatusNoContent}, nil
We're using the `models.responses.NewSuccessResponse()` function as the return wrapper - can this be changed for consistency:

`return models.NewSuccessResponse(nil, http.StatusNoContent, nil), nil`

2021-10-18 15:09 UTC, mike-kelly-methods approved these changes
👍

2021-10-18 15:24 UTC, merged