Feature/add component tests
ONSdigital/dp-identity-api pull request #8
Opened 2021-04-12 10:55 UTC by HeJones

### What

To enable features tests to be added to this service the following things have been done: 
- Add component tests to Make File
- Add features package to hold feature tests
- Added example tests to test the hello world endpoint - one is with a custom step, and one uses a step in the library
- Add ci files

### How to review

If you run `make test-component` the feature tests pass

### Who can review
Anyone

2021-04-12 12:01 UTC, nshumoogum requested changes

2021-04-12 12:01 UTC, nshumoogum commented on Makefile
> +	go test -cover -coverpkg=github.com/ONSdigital/dp-identity-api/... -component
Probably make sense to add -race flag after -cover?

2021-04-12 12:01 UTC, nshumoogum commented on ci/component.yml
> +    tag: 1.15.8
Bump to 1.16.3?

2021-04-12 12:01 UTC, nshumoogum commented on go.mod
go.mod file should be updated to latest go version 1.16

2021-04-12 12:01 UTC, nshumoogum commented on main_test.go
> +
Consider removing empty whitespace

2021-04-12 12:01 UTC, nshumoogum commented on main_test.go
> +		panic(err)
Would it not make more sense to use os.Exit(1)? And include a log line prior to exiting to log out the error?

2021-04-12 12:07 UTC, nshumoogum commented on ci/component.yml
> +    tag: 1.15.8
Probably want to bump tagged version in unit.yml and build.yml

2021-04-12 12:11 UTC, nshumoogum commented
github.com/gogo/protobuf - needs updating to use latest version 1.3.2 instead of 1.3.1 - hopefully this will resolve audit issues

2021-04-13 09:45 UTC, jon-acker commented on main_test.go
> +		panic(err)
yes, panic should def be removed, it would stop the test suite :)

2021-04-15 09:13 UTC, mike-kelly-methods commented on features/helloworld.feature
> +
Excessive number of newlines.

2021-04-15 10:06 UTC, mike-kelly-methods approved these changes
👍

2021-04-15 10:37 UTC, nshumoogum approved these changes

2021-04-15 11:06 UTC, merged